### ISSUE TITLE
Allow buliding for Lua 5.4

### ISSUE THREAD

**Issue by alerque** [siffiejoe/lua-luaepnf#4]
Right now the rockspec specifically precludes building this under the [recently released Lua 5.4](https://www.lua.org/versions.html#5.4). I don't know if that was an overly cautious block maneuver or if there is something it actually doesn't support, but either the block should be lifted so future new releases are allowed (until it's proven not to work) or whatever changes are needed for Lua 5.4 support should be added.

**Comment by alerque** [comment]
After merging that PR to enable Lua 5.4 support please also tag a release and update it on Luarocks so that I can start using this in production! Thank you.

**Comment by alerque** [comment]
Gentle poke on release (Luarocks & Git tag)...

**Comment by tst2005** [comment]
(typo in title `s/buliding/building/` )

**Comment by siffiejoe** [comment]
I've uploaded an updated rockspec four months ago, so luaepnf is already usable in Lua 5.4. The recent commits didn't change the code that get's installed, so a new release is not necessary at the moment.
